### ISSUE TITLE
Add tutorials

### ISSUE THREAD

**Issue by Coder-X15** [not-na/peng3d#5]
It would be great if you guys could put up a tutorial website which provides various tutorials using Peng3D :) ... I wish to know more on this.

**Comment by not-na** [comment]
Currently, I unfortunately do not have the time to write tutorials for peng3d. Once I do have time, I will write some (probably in the style of the pyglet docs).

What kind of tutorials do you have in mind? More basic stuff (hello world app, etc) or advanced topics (layered and custom widgets)?

Also, there are already some [examples](https://github.com/not-na/peng3d/tree/master/examples) in the repository. Some are a bit outdated, but should convey the general concepts just fine. I would recommend taking a look at the `gui_*.py` examples, as they showcase some of the more modern usecases.

I'll keep this issue open until we have at least some tutorials for people new to peng3d.

**Comment by Coder-X15** [comment]
My ideas are something like this: we'll use the programs in the examples folder as the examples in the tutorial, with modified versions added alongside to show various changes that show what happens when one like of code is changed. Or perhaps we can try and post a full tutorial on making a 3D game (perhaps Classic Minecraft; the newer versions can be made if the learner knows a bit of AI to automate the mobs. I'm not sure if my suggestion would be worthwhile, as I assess from your reply that the users might only need to glance through the code in 'examples'. I leave that decision to you :D.

**Comment by Coder-X15** [comment]
Sorry for my late reply (offline classes had started for me and so I had to get myself on the digital-detox mode 🤣 )... Thanks for your  actions. I hope you had also noticed that I made a small typo :"My ideas are something like this: we'll use the programs in the examples folder as the examples in the tutorial, with modified versions added alongside to show various changes that show what happens when one *_like_* of code is changed." It's not 'like' but it's 'line'.
